In [1]:
import numpy as np
import torch

Training Data

In [2]:
# temperature, rainfall, humidity
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
# apples, oranges
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Linear Regression Model from Scratch

In [5]:
# Weights and biases

w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w)
print(b)

tensor([[-1.9800, -0.6764,  1.5269],
        [ 1.3585,  0.7232, -1.2014]], requires_grad=True)
tensor([1.2764, 1.4536], requires_grad=True)


Our model definition

In [6]:
def model(x):
    return x @ w.t() + b

## .t() provides the transpor & '@' is for matrix multiplication

In [7]:
# generating predictions
preds = model(inputs)
print(preds)

tensor([[-122.9213,   97.4178],
        [-140.6998,  111.8287],
        [-173.0543,  146.8689],
        [-173.2684,  126.6665],
        [ -93.3905,   80.5188]], grad_fn=<AddBackward0>)


In [8]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss Function

In [9]:
## Mean Squared Error
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(25374.0625, grad_fn=<DivBackward0>)


Computing Gradients

In [11]:
# Compute gradients
loss.backward()

In [12]:
print(w)
print(w.grad)

tensor([[-1.9800, -0.6764,  1.5269],
        [ 1.3585,  0.7232, -1.2014]], requires_grad=True)
tensor([[-18422.5996, -19576.5254, -11958.7646],
        [  2136.8572,    961.9630,    660.0749]])


We need to reset the gradients back to zero to avoid unexpected results as it keeps adding the previous ones

In [13]:
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [14]:
w, b

(tensor([[-1.9800, -0.6764,  1.5269],
         [ 1.3585,  0.7232, -1.2014]], requires_grad=True),
 tensor([1.2764, 1.4536], requires_grad=True))