In [1]:
import torch

Pytorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array.

In [2]:
# number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# matrix
t3 = torch.tensor([[5.,6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# 3 dimensional array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])

t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [7]:
t4.shape

torch.Size([2, 2, 3])

Tensor Operations and Gradients

In [8]:
# creating tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [9]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

We can automatically compute the derivative of y w.r.t the tensors that have requires_grad set to True i.e. w & b. To compute the derivatives, we can call the ".backward" method on our result y.

In [10]:
# compute derivatives
y.backward()

The derivatives of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [11]:
print('dy/dx = ', x.grad)
print('dy/dw = ', w.grad)
print('dy/db = ', b.grad)

dy/dx =  None
dy/dw =  tensor(3.)
dy/db =  tensor(1.)


Interoperability with Numpy

In [12]:
import numpy as np 

x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
# converting the numpy array to a torch tensor
"""y = torch.from_numpy(x)
print(y)"""

'y = torch.from_numpy(x)\nprint(y)'

In [14]:
# use .numpy to get back the numpy array